language: node_js
node_js:
 - "8"
before_script:
 - npm install -g ionic cordova
script:
 - ionic build --prod --base-href 
# deploy:
# provider: pages
# skip-cleanup: true
# github-token: $GITHUB_TOKEN 
# keep-history: true
# on:
#   branch: master
# local_dir: www